Add --since and --ignore to git-recent-branches.

diff --git a/git-recent-branches b/git-recent-branches
--- a/git-recent-branches
+++ b/git-recent-branches
@@ -8,14 +8,41 @@
 # Copyright 2013 Mark Lodato <lodato@google.com>
 # Released under the MIT license; see LICENSE for details.
 
-# TODO Read max_age from git-config.  Validate it by comparing to --since=now.
-# TODO Read max_age from command-line argument.  Validate it as above.
-max_age='3 months ago'
-# TODO Read ignore_re from git-config.
-# TODO Read ignore_re from command-line argument.
+# TODO Default since from git-config.
+since='3 months ago'
+# TODO Default ignore_re from git-config.
 ignore_re='^junk/'
 
-min_timestamp=$(git rev-parse --since="$max_age" | sed -e 's/^--max-age=//')
+SUBDIRECTORY_OK=Yes
+OPTIONS_KEEPDASHDASH=
+OPTIONS_SPEC="\
+git recent-branches
+--
+since=          ignore branches whose most recent commit was older than this
+ignore=         ignore branches whose names match this regular expression
+"
+
+. git-sh-setup
+
+while test $# != 0
+do
+  case "$1" in
+    --since) since="$2" ; shift ;;
+    --ignore) ignore_re="$2" ; shift ;;
+    --) shift ; break ;;
+    *) break ;;
+  esac
+  shift
+done
+
+if [[ $# -ne 0 ]]; then
+  echo "error: no positional arguments are allowed" >&2
+  usage
+fi
+
+# TODO validate $since by comparing to "now".
+
+min_timestamp=$(git rev-parse --since="$since" | sed -e 's/^--max-age=//')
 current_branch=$(git symbolic-ref --short -q HEAD)
 
 git for-each-ref refs/heads --sort=committerdate \
